export default `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in libero porttitor, accumsan magna quis, bibendum sem. Nulla porttitor dapibus odio, tempus aliquam nisl mattis eu. Suspendisse in justo quis urna volutpat tempus. Vestibulum imperdiet dapibus diam quis porttitor. Donec vel dapibus arcu. Phasellus rhoncus massa ut turpis ultricies, suscipit vestibulum leo auctor. Quisque tempus tellus non velit molestie, ut volutpat sapien tempus. Aliquam erat volutpat.

Etiam pellentesque odio at urna imperdiet, id suscipit lorem auctor. In eu velit sed lorem tincidunt dapibus. Vivamus purus erat, lacinia non ante eu, maximus euismod augue. Ut mollis nunc nibh. Mauris in enim vitae mi tristique finibus sit amet in elit. Praesent nec libero sit amet felis elementum mattis quis quis mauris. Ut ipsum eros, rutrum at nunc nec, aliquet efficitur mi. Duis fringilla imperdiet quam, sit amet hendrerit dui porttitor porttitor. Quisque consequat orci eget imperdiet scelerisque. Etiam eu facilisis dolor, a porta metus. Morbi faucibus magna et lectus semper iaculis. In eu mauris quis ligula consectetur finibus sed ac odio.

Sed pellentesque, lectus eget pretium sodales, ipsum nibh luctus mauris, in bibendum lectus elit vitae urna. Donec pretium arcu sed mi varius dapibus. Etiam risus magna, fringilla ut urna et, pharetra eleifend ligula. Mauris vestibulum efficitur augue, id tincidunt dolor mollis id. Mauris sed commodo felis, nec vulputate orci. Duis finibus congue magna eget viverra. Nunc accumsan risus velit, et malesuada sapien consequat at. Nam vitae dui ac tellus sodales molestie ac vitae ipsum.

Sed varius dui a dolor scelerisque semper. Donec nisi ligula, maximus ut orci et, consectetur posuere dui. Sed augue eros, dignissim ut arcu nec, mollis aliquam mauris. Ut blandit quam vel dapibus iaculis. Nunc ultrices magna elementum leo aliquet laoreet. Aliquam erat volutpat. Cras sagittis gravida urna, a venenatis ipsum efficitur id. Cras pretium lacus sit amet congue consectetur. Suspendisse dolor ex, elementum in posuere ut, faucibus in urna.

Mauris mattis elementum orci, eget fermentum ligula viverra ut. In et lectus id ipsum hendrerit interdum. Donec sed tempus est. Donec egestas tincidunt dignissim. Integer pellentesque, sapien ut bibendum pharetra, velit quam aliquet libero, non tincidunt leo diam at leo. Vivamus condimentum ligula sed molestie interdum. Morbi felis lorem, volutpat et scelerisque non, ullamcorper eget nisl. Maecenas dapibus lacinia molestie. Morbi sollicitudin, ligula quis commodo ultricies, mi tellus interdum ligula, at dapibus lorem nisi vitae libero. Integer dignissim eros eget arcu scelerisque aliquet. Fusce lacinia ex nec iaculis commodo. Vestibulum tempus turpis a massa scelerisque, et suscipit nisi suscipit. `;
